
title: Safety Blog
email: your-email@example.com
description: Workplace safety blog

baseurl: "http://safetyworkblog.com" 
url: 'http://safetyworkblog.com'
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
sass:
  sass_dir: _sass
  include: ['_pages']
kramdown:
  input: GFM
